### ISSUE TITLE
Disable persisting counter examples for specific tests

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#105]
I have a generator which takes its allowed values from a database. For each invocation of `mix test`, a migration is run where such values are inserted into a database. After the test, the database is rolled back. This results in different row ids over subsequent test runs. Now, if a counter example is found, the stored counter example will not match any stored entry in the database on the next run. I would like to explicitly mark a property to not store the counter example upon error:

```elixir
@tag counter_example: false
property "do not store counter example" do
  ...
end
```

**Comment by evnu** [comment]
@alfert Please give a heads-up if you want that feature. I would put up a pull request then.

**Comment by alfert** [comment]
I was thinking whether this is a solution for your problem, but I am missing information for that. Just the quick idea that you perhaps can filter out the row ids inside the data generator to achieve a persistible counter example. 

But let's go for it. I think it is crucial to document clearly that this is for exceptional cases, since we generally advise to work with counter examples. I suggest to call the tag `store_counter_example`, because it is only concerned with the persistency aspect not about finding and shrinking a counter example.

**Comment by alfert** [comment]
Ah, yes, for sure, if you need to check that your property results match an uncontrolled database, then you have only very limited options.  No chance to generate the relevant input values? Something like 

    forall l <- list(integer) do
       create_new_customers_with_ids(l) 
       run_the_transactions()
       check_the_property()
    end

But nevertheless, your idea is nice and helpful, so I am looking forward to your PR!
