### ISSUE TITLE
StateM.DSL vs PropEr differences

### ISSUE THREAD

**Issue by x4lldux** [alfert/propcheck#142]
I've started digging into StateM.DSL while working on generating reports and I've realized it cannot be done, with the same feature set, unless introducing some breaking changes.
But what's more important, translating from tests in _StateM_-ecosystem into _StateM.DSL_-ecosystem was not straight forward because of many differences in interface but also in behaviour:

- when a command crashes StateM.DSL catches it, and continues execution and returns the sequence as successful :confounded: ,
- a crash in postcondition works the same way as a crash in command,
- crash in precondition crashes the test,
- crash in state initialization also crashes the test,
- symbolic datatypes are not fully supported,

While in StateM/PropEr all those crashes just generate a informative return type with a consistent `:exception` tuple. There might be more differences.

So, since we've already introduced some braking changes in #141 and implementing reports would also need to do more of them, why not just reimplement DSL on top of PropEr completely?
This would relieve us from maintaining a replica of the PropEr code and focus on wrapping code instead. 

Of course, that would probably change some (most?!) of the returns types but the DSL would stay mostly the same.

**Comment by alfert** [comment]
Thank you for this review, you seem to be the first, who looked deep enough into this. :green_heart:

> why not just reimplement DSL on top of PropEr completely?

Depends on what you mean exactly. We should fix the crashing, in particular the first one, because it is obviously a bug. Any ideas for supporting symbolic datatypes are highly welcome. But what we cannot do is to implement the DSL on top of PropEr, because PropEr does not have this feature. The DSL is more of a kind of implementing the corresponding QuickCheck feature, since it is a different view on state machines (PropEr and the QuickCheck state machines focus on the states, but the DSL is structured around the transitions/commands). This is the reason for introducing similar and quite complex yet different generators. I would prefer to write a simple wrapper on top of PropEr, but I found no pragmatic way of doing that. At least you would have to implement quite complex macros that generate parts of function bodies that need to be copied to together. But perhaps my thoughts about translating these state machines models into each other were not deep enough and there is some straight and easier way to achieve that.  

If (too many) breaking changes for user code are required to achieve a better reporting including fixing the mentioned inconsistencies and bugs, then I would prefer a second implementation (DSL2) and we deprecate the old one (either as soft or hard deprecation). After a quick look into the Cache example, I do not see at first glance where breaking changes would appear. Can you already foresee where this well be the case?

**Comment by x4lldux** [comment]
> Depends on what you mean exactly.

Something like [this](https://github.com/x4lldux/propcheck/commit/726c943eaeba55d72114ad5312a49ff50815ccde).

> At least you would have to implement quite complex macros that generate parts of function bodies that need to be copied to together. 

Actually not. Most of the "hard stuff" you have already done. What I've change was just [those lines](https://github.com/x4lldux/propcheck/commit/726c943eaeba55d72114ad5312a49ff50815ccde#diff-08986d5e1d1ce9ad6230b6d533c59f34R97-R152). The rest is mostly a copy from `PropCheck.StateM`. There's also an example how to use it in test/statem_dsl2_test.exs 

It's obviously not done yet. I didn't finish the `@impl` stuff, where either the `proper_statem` or `PropCheck.StateM.DSL` behavour will be used.

Also, I've dropped `weight` and `args` functions in favor of `command_seq` callback - it's both easier to implement, but more importantly, grouping the command generation and sequencing together is more natural (for more rationale see [comment](https://github.com/x4lldux/propcheck/commit/726c943eaeba55d72114ad5312a49ff50815ccde#diff-08986d5e1d1ce9ad6230b6d533c59f34R40)).
 more about that is in

**Comment by alfert** [comment]
That is short and to the point at first glance. I need to meditate a bit over it. 

Removing the `weight`  and `args` is the major incompatibility, correct?

**Comment by x4lldux** [comment]
@alfert Yes. And also some types and return values of functions like `run_commands`. Old one returned a custom map with history and state entangled, a "new" one is Plain Old™ `:proper_statem.return_value`.

I'm pushing for this, because I'm toying with an idea of adding something like "semantic printing" to the PropEr, which would allow for further elixirfying printouts (for example, printing minimization progress is still ugly). So implementing as much as possible using PropEr would relive us from duplicating the same thing in both libraries.

**Comment by alfert** [comment]
> So implementing as much as possible using PropEr would relive us from duplicating the same thing in both libraries. 

That's a good point. It was one of the benefits in the DSL to be closer to Elixir and all the Erlang printouts are really a bad thing from a user's perspective

**Comment by x4lldux** [comment]
And a bonus point: I don't need to do any changes to `StateM.Reporter` :grin:

**Comment by alfert** [comment]
We can close this one since #147 is merged.
