### ISSUE TITLE
Consider adding open source code exemption to current license

### ISSUE THREAD

**Issue by paulperegud** [alfert/propcheck#56]
Something of this kind:

https://github.com/proper-testing/proper/issues/29#issuecomment-4956226

**Comment by alfert** [comment]
Actually PropCheck inherits the licensing from PropEr due to GPL's copyleft. But to link to that discussion is a good idea. I would like to use LGPL, which is IMHO better suited the GPL with PropEr's Open Source exception: Development of PropCheck would be protected by copyleft, but all projects can use PropCheck/PropEr in their tests without fearing to become infected by copyleft.
