### ISSUE TITLE
remove _build/propcheck.ctex by default

### ISSUE THREAD

**Issue by verrchu** [alfert/propcheck#81]
I have seen warnings for Elixir user to remove the `_build/propcheck.ctex` file in order to always get fresh results by the generators.
It is superannoying to remove the file by hand every time
Why not just remove it by default?

**Comment by alfert** [comment]
Yes, it is exactly the way, evnu describes. The basic idea behind is that you focus on getting failing properties right and get the always the same counterexample until the properties is no longer failing (i.e. the bug is fixed - assuming that the property is correct and so is the generator). 

@verrchu, is your problem that this development approach is not clearly enough stated in the docs or does not fit to your way of development? This feature was introduced to support developing and not annoy developers.

**Comment by adkron** [comment]
If this is something that won't be changed could we close it so that someone looking for something to work on won't come and read it?

**Comment by verrchu** [comment]
@adkron yes sure
thanks for your help
