### ISSUE TITLE
Consider using Linter

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#98]
I think the code base and CI might benefit from a linter. I found [credo](https://github.com/rrrene/credo) useful in other projects. If there is interest for this, I will put up a PR.

**Comment by alfert** [comment]
I worked with credo once in a while. My experience was generally good, but I found that the settings are partially something like personal style (similar to the Elixir formatter). So, we need careful regarding the settings and I would assume that a lot of annoying bugs/warnings may be introduced due to adding it a greater and older existing code base.

But yes, there are so many formatting issues in propcheck that it really may be good idea to make it more consistent proactively. Looking forward to your PR.

**Comment by evnu** [comment]
Yes, we will need to adapt credo's configuration to match the code base. I will put up a PR without fixing the lints and we can discuss which of them are actual problems and which should result in a change to the configuration.
